<?php

/**
 * Implements hook_mail().
 */
function culturefeed_udb3_mail($key, &$message, $params) {
  switch ($key) {
    case 'event_export_ready':
      $message['subject'] = 'Uw export van evenementen';
      $message['body'][] = $params['location'];

      break;
  }
}

/**
 * Implements hook_install().
 */
function culturefeed_udb3_install() {
  $exportLocation = \Drupal::getContainer()
    ->getParameter('culturefeed_udb3.export_folder_location');

  /** @var \Drupal\Core\File\FileSystem $fileSystem */
  $fileSystem = \Drupal::service('file_system');

  $fileSystem->mkdir($exportLocation);
}
